// default package
// Generated 23 abr 2022 20:24:38 by Hibernate Tools 5.6.3.Final
package com.marc.HibernateAnotaciones03;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autores generated by hbm2java
 */
@Entity
@Table(name = "autores")
public class Autores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "cod", unique = true, nullable = false, length = 5)
	private String cod;
	@Column(name = "nombre", length = 60)
	private String nombre;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autores")
	private Set<Escribir> escribirs = new HashSet<Escribir>(0);

	public Autores() {
	}

	public Autores(String cod) {
		this.cod = cod;
	}

	public Autores(String cod, String nombre, Set<Escribir> escribirs) {
		this.cod = cod;
		this.nombre = nombre;
		this.escribirs = escribirs;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Escribir> getEscribirs() {
		return this.escribirs;
	}

	public void setEscribirs(Set<Escribir> escribirs) {
		this.escribirs = escribirs;
	}

}
