// default package
// Generated 23 abr 2022 20:24:38 by Hibernate Tools 5.6.3.Final
package com.marc.HibernateAnotaciones03;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Escribir generated by hbm2java
 */
@Entity
@Table(name = "escribir")
public class Escribir implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "codautor", column = @Column(name = "codautor", nullable = false, length = 5)),
		@AttributeOverride(name = "codlibro", column = @Column(name = "codlibro", nullable = false)) })
	private EscribirId id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codautor", nullable = false, insertable = false, updatable = false)
	private Autores autores;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codlibro", nullable = false, insertable = false, updatable = false)
	private Libros libros;
	@Column(name = "anyo")
	private Integer anyo;

	public Escribir() {
	}

	public Escribir(EscribirId id, Autores autores, Libros libros) {
		this.id = id;
		this.autores = autores;
		this.libros = libros;
	}

	public Escribir(EscribirId id, Autores autores, Libros libros, Integer anyo) {
		this.id = id;
		this.autores = autores;
		this.libros = libros;
		this.anyo = anyo;
	}

	public EscribirId getId() {
		return this.id;
	}

	public void setId(EscribirId id) {
		this.id = id;
	}

	public Autores getAutores() {
		return this.autores;
	}

	public void setAutores(Autores autores) {
		this.autores = autores;
	}

	public Libros getLibros() {
		return this.libros;
	}

	public void setLibros(Libros libros) {
		this.libros = libros;
	}

	public Integer getAnyo() {
		return this.anyo;
	}

	public void setAnyo(Integer anyo) {
		this.anyo = anyo;
	}

}
