// default package
// Generated 18 abr 2022 23:29:39 by Hibernate Tools 5.6.3.Final
package com.marc.HibernateAnotaciones02;
import java.util.HashSet;
import java.util.Set;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table; 

/**
 * Libros generated by hbm2java
 */
@Entity
@Table(name = "libros")
public class Libros implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id 
	@Column(name = "id", unique = true, nullable  = false)
	private int id;
	@Column(name = "titulo", length = 60)
	private String titulo;
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "escribir", joinColumns = {
			@JoinColumn(name = "codlibro", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codautor", nullable = false, updatable = false) })
	private Set<Autores> autoreses = new HashSet<Autores>(0);

	public Libros() {
	}

	public Libros(int id) {
		this.id = id;
	}

	public Libros(int id, String titulo, Set<Autores> autoreses) {
		this.id = id;
		this.titulo = titulo;
		this.autoreses = autoreses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Set<Autores> getAutoreses() {
		return this.autoreses;
	}

	public void setAutoreses(Set<Autores> autoreses) {
		this.autoreses = autoreses;
	}

}
